##pubspec.yaml file
name: eventhub
description: A lightweight localized event management app for grassroots organizers.
publish_to: 'none' 
version: 0.1.0


environment:

  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  # Image handling and HTTP
  http: ^1.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2

  # State management
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Firebase dependencies
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true