name: eventhub
description: A lightweight localized event management app for grassroots organizers.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true